### ISSUE TITLE
client.js: createHolidayRequest: keine Beschreibung für Sonderurlaub

### ISSUE THREAD

**Issue by mklw92** [danielnassauer/swtp-urlaubsverwaltung#14]
Da fehlt ein Feld für den Grund des Sonderurlaubs. Den können wir im Moment noch nicht übergeben.

**Comment by danielnassauer** [comment]
Werde wahrscheinlich die Nummern als Typ eines Antrags entfernen und stattdessen direkt Strings als Bezeichnung verwenden
